### ISSUE TITLE
Get logp from SGMCMC

### ISSUE THREAD

**Issue by rzu512** [thu-ml/zhusuan#123]
The `HMC` class allows accessing the log-joint probability before and after the update step through the `log_prob` and `orig_log_prob` attributes of the `HMCInfo` class. However, the stochastic gradient MCMC classes in zhusuan don't expose these two log-joint probabilities.

Is it possible to get a tensorflow operation for the log-joint probability at the end of the update step in `SGMCMC`? Or alternatively Is it possible to get a tensorflow operation for the value of the parameters before the update step?

**Comment by csy530216** [comment]
Hello, I think it is not difficult to get the value of the parameters as long as you perform something like `sess.run(latent)`. About the log-joint probability, since in SGMCMC algorithm we do not need to compute it (unlike in HMC, since we need to perform the Metropolis-Hastings step there), by default the `log_prob` is not returned (to reduce the size of computation graph).

If you want to get `log_prob` given the value of parameters stored in a dictionary `latent`, you could add some codes in your script as follows:
```python
bn = model.observe(**merge_dicts(latent, observed))
log_prob = bn.log_joint()
```

**Comment by rzu512** [comment]
In the end, I modify my joint_prob function to store the logp and parameters at the half step. For my case, I only need to do one additional sum to get the logp after calculating the gradient. So it make sense to calculate the gradient and logp at the same time t.
