### ISSUE TITLE
pairwise Markov random field

### ISSUE THREAD

**Issue by DanqingZ** [thu-ml/zhusuan#61]
dear authors, thanks for this package. I am wondering if Markov random field can be implemented using zhusuan, is so, do you have a tutorial for me to go through? thank you.

**Comment by thjashin** [comment]
Unfortunately, as most of probabilistic programming libraries, we currently only support directed models. How to deal with undirected models in a general way is still an open problem for probabilistic programming.

If you are using MRFs for structured prediction, I guess deep generative models can do equally well (even much better).

**Comment by thjashin** [comment]
Wait, what kind of markov random field are you dealing with? @cjf00000 made me realize that you can deal with continuous markov random field with zs.HMC.

**Comment by DanqingZ** [comment]
@thjashin  I am having a high-order Markov random field that is a part of my larger model, I am now using some MCMC techniques, but it is too slow, so I am looking for some alternatives.

**Comment by thjashin** [comment]
@DanqingZ Ok, that's clear. I think there are several ways to address this problem,
* Have you heard about [Perturb-and-MAP](https://pdfs.semanticscholar.org/3449/0cf2694a66c292d2d6ba69215c963fb2f5fd.pdf)? This a trick to sample from discrete MRFs. Once you have samples, you can use EM for parameter learning.
* Alternatively you can make use of ZhSuan. You can use the [Gumbel-softmax trick](https://arxiv.org/pdf/1611.01144.pdf), or [Concrete distribution](https://arxiv.org/pdf/1611.00712.pdf) (See [ZhuSuan's Concrete distribution](https://github.com/thu-ml/zhusuan/blob/master/zhusuan/distributions/multivariate.py#L505)) to transform your model into a continuous MRF, and then you can use `zs.HMC` to sample from it (faster than plain Gibbs since you could work in the whole latent space and use parallel chains on GPUs).

**Comment by DanqingZ** [comment]
Thanks! let me check the links.

**Comment by DanqingZ** [comment]
@thjashin , what is the capacity of zhusuan with continuous MRF? Can it deal with thousands of nodes or even millions of nodes? thanks.

**Comment by thjashin** [comment]
That really depends on whether your tuned HMC is scalable to thousands of dimensions (whether it can efficiently explores the space). I don't have much experience for this specific scene but you could give it a try first with tens of nodes to see how it works.

On the computation side, when you have large models, you may do it with a mix of Gibbs and HMC, that is, you could divide the total nodes into several groups, and use Gibbs as an outer loop, with the inner step as a HMC iteration.

**Comment by DanqingZ** [comment]
Hi, Could you point me to where the continuous markov random field is used? It looks to me most of the models in the tutorial uses bayes net, which is directed.

**Comment by thjashin** [comment]
I may write a small prototype (with two or three nodes) when I have free time. Maybe @miskcoo can help also?

**Comment by DanqingZ** [comment]
@thjashin @miskcoo , sure, a small prototype, with fewer than 10 nodes, is enough for me to learn.  Thanks.

**Comment by thjashin** [comment]
@DanqingZ See #62 for a simple gaussian markov random field with 2 nodes, using HMC to sample.

**Comment by DanqingZ** [comment]
@thjashin  Thank you! let me check it.

**Comment by misssprite** [comment]
Hi, @thjashin 
I plan to do some unsupervised images segmentation. It seem that MRF makes sense and I'm wondering if it can be accelerated with gpu.
What do you mean by 'deep generative models'? VAE?
Could you give me some suggestion of some work on unsupervised images segmentation?
