### ISSUE TITLE
HMC parameters settings

### ISSUE THREAD

**Issue by ifangcheng** [thu-ml/zhusuan#89]
in examples:    gaussian.py

# Define HMC parameters
    kernel_width = 0.1
    n_chains = 1000
    n_iters = 200

what is the diffetence between n_chains and n_iters?

it seems that both of them affect the final sampling quality?

what is exactly the difference if i change them as follows: 
n_chains = 100  
n_iters = 2000

**Comment by thjashin** [comment]
`n_chains` stands for how many MCMC chains you are simulating in parallel. `n_iters` represents how long you simulate, say, `n_chains = 100, n_iters = 2000` means you simulate all the chains for 2000 iterations.

**Comment by ifangcheng** [comment]
ok, i see
but
n_chains = 100
n_iters = 2000
vs
n_chains = 1000
n_iters = 200

normally, which one will be better?

**Comment by thjashin** [comment]
They are independent of each other. In general, `n_iters` should be sufficiently large so that the chain will mix. It only depends on the problem. For `n_chains`, you can think of it as `n_threads` in parallel programming. More is better, which means you can get more samples in the same amount of running time, but for large models, typically you cannot afford a too large `n_chains`.

**Comment by ifangcheng** [comment]
it seems like a kind of particle filter
many thx!

**Comment by thjashin** [comment]
You're welcome.
