### ISSUE TITLE
Clarification on HMC

### ISSUE THREAD

**Issue by botev** [thu-ml/zhusuan#90]
I have two questions regarding the HMC implementation:

1. Why the default `target_acceptance_rate` is 0.8 and not 0.65, which is most widely used in the literature.
2. Is there a white paper about the method used for adapting the mass? (I assume this is the diagonal covariance of the velocity vectors)

**Comment by thjashin** [comment]
My guess is
1. For deep models, usually smaller step sizes are needed.
2. Yes (a moving average of it), learnt from Stan's code. Their [manual](http://mc-stan.org/users/documentation/) has a few words on it.

But let @cjf00000 answer the questions.

**Comment by botev** [comment]
Ah, not to be critical, but I could not find anything on their manual page and it seems quite unintuitive at least to me. I was asking as I wanted to run the HMC code on a custom model (e.g. I need a separate HMC implementation) and I'm aware of the dual averaging from the NUTS paper but have not seen the mass adaptation before, so I wanted a reference text on that.

**Comment by cjf00000** [comment]
Regarding to the step size
----

I set the step size to be 0.8 because in practice I found it performs better than 0.6 or 0.65, on logistic-normal topic models and VAEs. Sometimes 0.9 works even better.

Regarding to the mass
----

It seems that adapting mass is from paper [1], according to Matt Hoffman [2]. I have not read that paper either, and the adaptation strategy is just taken from Stan, as @thjashin mentioned. 

Maybe looking at a multivariate Gaussian case helps. Suppose we want to sample from a Gaussian N(0, \Sigma^-1), where the diagonal covariance \Sigma_{ii} differs a lot in the scale. In this case the step size is limited by the smallest \Sigma_ii. 

By computing the covariance we can approximately get Mass = \Sigma^-1. The momentum will be scaled by sqrt(Mass)=Sigma_ii^{-0.5} on dimension i, and the move will be scaled by momentum/Mass = Mass^-0.5=Sigma_ii^{0.5}, which is correct in this case. I think letting the mass to be the covariance of p is the same, at least in this case. I didn't compare them though. 

Regarding to the adaption of the number of leapfrog steps
----

NUTS can have different number of leapfrogs for different chains. So we can't vectorize NUTS to run many chains in parallel. Additionally, it is too difficult to implement NUTS as a computation graph. 

In the early stage of the development, we have implemented single-chain NUTS. The implementation accepts a `tf.Session` and calls `sess.run()` for many times inside the `sample` method (resembles to PyMC3). But we didn't find NUTS to be better than HMC though. 

[1] Charles H Bennett. Mass tensor molecular dynamics. Journal of Computational Physics, 19(3):267–279, 1975.
[2] Levy, Daniel, Matthew D. Hoffman, and Jascha Sohl-Dickstein. "Generalizing Hamiltonian Monte Carlo with Neural Networks." arXiv preprint arXiv:1711.09268 (2017).
