### ISSUE TITLE
confusions about lb_z  in vae_ssl.py

### ISSUE THREAD

**Issue by ifangcheng** [thu-ml/zhusuan#95]
1. From line 124 of  vae_ssl.py, it seems that lb_z  is a zs.variational.elbo object.
however, from line 130:
lb_z = tf.reshape(lb_z, [-1, n_y])
it seems that  lb_z  is treated as a tensor.  so, what exactly lb_z is?  how is it calculated?

2. line 136-137:
   unlabeled_lower_bound = tf.reduce_mean(tf.reduce_sum(qy_u * (lb_z - log_qy_u), 1))

which makes me confused.  
why use lb_z again here to calculate unlabeled_lower_bound ?   what's the math behind the expression?

As according to the ELBO expression,  it seems that is should be something like this: unlabeled_lower_bound = tf.reduce_mean(tf.reduce_sum(qy_u * ( logpθ(x,y,z)- log_qy_u), 1))
why here use lb_z  instead of something like   logpθ(x,y,z)

**Comment by thjashin** [comment]
> From line 124 of vae_ssl.py, it seems that lb_z is a zs.variational.elbo object.
however, from line 130:
lb_z = tf.reshape(lb_z, [-1, n_y])
it seems that lb_z is treated as a tensor. so, what exactly lb_z is? how is it calculated?

Instances of `VariationalObjective` are Tensor-like. See the doc string [here](https://github.com/thu-ml/zhusuan/blob/master/zhusuan/variational/exclusive_kl.py#L29). 
This example follows from the Kingma(2014) [paper](https://arxiv.org/abs/1406.5298). And `lb_z` corresponds to Equation 6 in the paper.

> line 136-137:
unlabeled_lower_bound = tf.reduce_mean(tf.reduce_sum(qy_u * (lb_z - log_qy_u), 1))

Because you need to manually sum over the discrete latent variables (y). See  Equation 7 in the [paper](https://arxiv.org/abs/1406.5298). For a cleaner implementation, you can use some inference methods that works for both discrete (y) and continuous latent variables (z). See this [example](https://github.com/thu-ml/zhusuan/blob/master/examples/semi_supervised_vae/vae_ssl_rws.py) that uses importance sampling instead.

**Comment by ifangcheng** [comment]
thanks for these references, now  all make sense!

**Comment by ifangcheng** [comment]
thanks for these references, now  all make sense!

**Comment by ifangcheng** [comment]
Thanks for these references, now  all make sense!
